[[language]]
name = "rust"

[language.config]
checkOnSave = { command = "clippy" }

[[language]]
name = "astro"
file-types = ["astro"]
comment-token = "//"
language-server = {command = "astro-ls", args = ["--stdio"] }

