[[language]]
name = "rust"

[language.config]
checkOnSave = { command = "clippy" }

[[language]]
name = "astro"
file-types = ["astro"]
comment-token = "//"
language-server = {command = "astro-ls", args = ["--stdio"] }

[[language]]
name = "python"
file-types = ["py"]
roots = ["pyproject.toml", "setup.py", "Poetry.lock", ".git"]
language-server = { command = "pyright-langserver", args = ["--stdio"] }
# auto-format = true
# formatter = {command = 'black', args = ["--quiet", "-"]}
# config = ""
